Models
MaksimPilskii/test-guru pull request #5
Opened 2022-04-18 14:31 UTC by MaksimPilskii

added an instance of the test_level method and a method of the sorting_an_array class

2022-04-18 15:42 UTC, VidgarVii requested changes

2022-04-18 15:42 UTC, VidgarVii commented on app/models/test.rb
> +    .where('categories.title = ?', category)
лучше всего, где это возможно, использовать "хеш-синтаксис
обычно это лаконичней и легче править
```ruby
.where(categories: { title: **category_title**  })
```

2022-04-18 15:42 UTC, VidgarVii commented on app/models/test.rb
> +    Test.joins('JOIN categories ON categories.id = tests.category_id')
можно (и рекомендуется)  писать так:
```ruby
joins(...)...
```
т.е. без явного указания объекта у которого вызывается метод
потому что в данном случае объектом является класс `Test` и ему равен `self` внутри класс-метода
по дефолту, при вызове метода без указания объекта он вызывается у `self`, т.е. в текущем варианте как раз у `Test`

2022-04-18 15:42 UTC, VidgarVii commented on app/models/test.rb
> +  def self.added an instance of the test_level method and a method of the sorting_an_array class(category)
пожалуйста, тестируй код!

2022-04-18 15:42 UTC, VidgarVii commented on app/models/user.rb
> +    .where("level = #{level}")
хеш синтаксис безопасней интерполяции

2022-04-18 15:42 UTC, VidgarVii commented on db/seeds.rb
> +TestUser.create!(user_id: 1, test_id: 1)
"хардкодить" `id` - не очень хорошая затея
такой "сид" невозможно накатить на существующую базу, ведь там id могут быть заняты другими записями или вовсе отсутствовать
правильней воспользоваться тем, что метод `create` возвращает созданные записи

2022-04-18 15:42 UTC, VidgarVii commented on db/seeds.rb
> +TestUser.create!(user_id: 2, test_id: 3)
create! может принимать массив данных. Смотри пример на 6 строке

2022-04-18 15:59 UTC, MaksimPilskii commented on app/models/test.rb
> +  def self.added an instance of the test_level method and a method of the sorting_an_array class(category)
Код тестировал. Это недосмотрел, когда писал комментарий. Спасибо.

2022-04-20 16:28 UTC, VidgarVii requested changes

2022-04-20 16:28 UTC, VidgarVii commented on db/seeds.rb
> +Answer.create!(body: "<java>", question_id: 2)
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file

2022-04-22 05:29 UTC, merged